In [42]:
import pandas
import numpy
from sklearn.metrics import r2_score, mean_squared_error
from sklearn.ensemble import RandomForestRegressor

In [43]:
data_test = pandas.read_csv('../database/traffic_site_test.csv', sep=';')
data_test.head()

,visitNumber,browser,operatingSystem,isMobile,deviceCategory,country,visits,hits,pageviews,bounces,...,medium,isTrueDirect,year,month,day,quarterMonth,weekday,time_range,buy,transactionRevenue
0,0.693147,1.791759,2.302585,0.000000,0.000000,4.317488,0.693147,0.693147,0.693147,0.693147,...,1.791759,0.000000,7.609862,0.693147,3.367296,0.693147,1.791759,1.386294,0,0.0
1,1.609438,1.791759,1.945910,0.000000,0.000000,4.934474,0.693147,1.386294,1.386294,0.000000,...,1.791759,0.693147,7.609862,1.609438,3.258097,1.098612,0.693147,1.609438,0,0.0
2,1.386294,1.791759,0.693147,0.693147,0.693147,4.934474,0.693147,2.484907,2.397895,0.000000,...,1.791759,0.000000,7.609862,1.098612,2.772589,0.693147,1.098612,0.693147,0,0.0
3,0.693147,1.791759,0.693147,0.693147,0.693147,3.784190,0.693147,0.693147,0.693147,0.693147,...,1.791759,0.000000,7.609367,2.564949,2.833213,1.609438,1.609438,1.386294,0,0.0
4,0.693147,1.791759,1.791759,0.000000,0.000000,4.934474,0.693147,0.693147,0.693147,0.693147,...,1.791759,0.000000,7.609862,1.791759,2.833213,1.098612,0.693147,1.386294,0,0.0

In [44]:
data_train = pandas.read_csv('../database/traffic_site_train.csv', sep=';')
data_train.head()

,visitNumber,browser,operatingSystem,isMobile,deviceCategory,country,visits,hits,pageviews,bounces,...,medium,isTrueDirect,year,month,day,quarterMonth,weekday,time_range,buy,transactionRevenue
0,0.693147,1.791759,1.945910,0.0,0.0,4.934474,0.693147,0.693147,0.693147,0.693147,...,1.945910,0.000000,7.609862,1.098612,2.890372,0.693147,1.609438,1.386294,0,0.0
1,0.693147,1.791759,1.386294,0.0,0.0,4.934474,0.693147,1.386294,1.386294,0.000000,...,1.791759,0.000000,7.609367,2.397895,2.890372,1.609438,0.000000,0.000000,0,0.0
2,0.693147,1.791759,2.302585,0.0,0.0,4.430817,0.693147,1.098612,1.098612,0.000000,...,1.791759,0.000000,7.609367,2.484907,2.484907,1.609438,1.609438,1.098612,0,0.0
3,0.693147,1.791759,2.302585,0.0,0.0,4.025352,0.693147,1.098612,1.098612,0.000000,...,0.000000,0.693147,7.609862,1.098612,3.295837,0.693147,1.945910,0.000000,0,0.0
4,0.693147,1.791759,2.302585,0.0,0.0,4.927254,0.693147,0.693147,0.693147,0.693147,...,1.791759,0.000000,7.609862,1.609438,3.401197,1.098612,1.791759,0.000000,0,0.0

In [45]:
# data_test = data_test.drop(columns=['visits', 'bounces', 'campaign'])
# data_train = data_train.drop(columns=['visits', 'bounces', 'campaign'])

In [46]:
x_train = data_train.drop(columns='transactionRevenue')
y_train = data_train['transactionRevenue']

x_test = data_test.drop(columns='transactionRevenue')
y_test = data_test['transactionRevenue']

Entrenamos el modelo

In [47]:
model = RandomForestRegressor(random_state=123)
model.fit(x_train, y_train)

RandomForestRegressor(random_state=123)

In [48]:
predictions = model.predict(x_test)
predictions

array([0., 0., 0., ..., 0., 0., 0.])

Evaluamos el desempeÃ±o

In [49]:
r2 = r2_score(y_test, predictions)
rmse = numpy.sqrt(mean_squared_error(y_test, predictions))

print(f'r2: {r2}')
print(f'rmse: {rmse}')

r2: 0.6878431815249655
rmse: 1.1792731829633412

In [50]:
rmse/1000000

1.1792731829633412e-06

In [51]:
model.feature_importances_

array([2.22110412e-02, 2.68227249e-03, 2.06245105e-02, 1.22523021e-03,
       1.89713005e-03, 2.21796063e-03, 0.00000000e+00, 3.75114960e-02,
       3.72704665e-02, 0.00000000e+00, 1.62704352e-03, 1.31732094e-04,
       1.29966026e-02, 8.25298845e-03, 5.46565157e-03, 1.56947319e-03,
       2.52794982e-02, 3.20682934e-02, 7.61630716e-03, 1.81034133e-02,
       1.20784189e-02, 7.49170470e-01])

In [52]:
model.feature_names_in_

array(['visitNumber', 'browser', 'operatingSystem', 'isMobile',
       'deviceCategory', 'country', 'visits', 'hits', 'pageviews',
       'bounces', 'newVisits', 'campaign', 'source', 'medium',
       'isTrueDirect', 'year', 'month', 'day', 'quarterMonth', 'weekday',
       'time_range', 'buy'], dtype=object)

In [53]:
obj={
 'features': model.feature_names_in_,
 'importances': model.feature_importances_
}
features = pandas.DataFrame(data=obj)
features.sort_values(by='importances')

           features  importances
6            visits     0.000000
9           bounces     0.000000
11         campaign     0.000132
3          isMobile     0.001225
15             year     0.001569
10        newVisits     0.001627
4    deviceCategory     0.001897
5           country     0.002218
1           browser     0.002682
14     isTrueDirect     0.005466
18     quarterMonth     0.007616
13           medium     0.008253
20       time_range     0.012078
12           source     0.012997
19          weekday     0.018103
2   operatingSystem     0.020625
0       visitNumber     0.022211
16            month     0.025279
17              day     0.032068
8         pageviews     0.037270
7              hits     0.037511
21              buy     0.749170